version: '3.7'  # optional since v1.27.0
services:
  app:
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "***"
      ACCEPT_EULA: "***"
    volumes:
      - mssql-data:/var/opt/mssql
volumes:
  mssql-data:
